name: Detect Pull Request Preview
on: deployment
jobs:
  detect-deployment:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install dependency
      run: pip install requests
    - name: Detect deployment
      run:
        ./tools/ci/debug_deploy.py
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
