name: Synchronize Pull Request Previews
on:
  schedule:
    - cron: 0/5 * * * *
jobs:
  update-pr-preview:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install dependency
      run: pip install requests
    - name: Trust GitHub.com for SSH
      run:
        mkdir -p ~/.ssh;
        echo github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
          >> ~/.ssh/known_hosts
    - name: Synchronize state
      run:
        ./tools/ci/update_pr_preview.py
          --host https://api.github.com
          --github-project web-platform-tests/wpt-actions-test
          --repository git@github.com:web-platform-tests/wpt-actions-test.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

