name: Synchronize Pull Request Previews
on:
  schedule:
    - cron: 0/5 * * * *
jobs:
  update-pr-preview:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install dependency
      run: pip install requests
    - name: Synchronize state
      run:
        ./tools/ci/update_pr_preview.py
          --host https://api.github.com
          --github-project web-platform-tests/wpt-actions-test
          --remote origin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

